export enum UniswapV3Contracts {
    NONFUNGIBLE_POSITION_MANAGER_CONTRACT = "NONFUNGIBLE_POSITION_MANAGER_CONTRACT",
    POOL_FACTORY_CONTRACT = "POOL_FACTORY_CONTRACT",
}

export enum LivecycleEvents {
    MINT = "MINT",
    INCREASE = "INCREASE",
    DECREASE = "DECREASE",
    COLLECT_FEES = "COLLECT_FEES",
    BURN = "BURN",
}
