#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚧 check types, format and lint before commiting"
yarn check-types || (
    echo "🙁 types check failed"
    false;
)

yarn check-format || (
    echo "🙁 format check failed"
    false;
)

yarn check-lint || (
    echo "🙁 lint failed"
    false;
)

echo "...fine, code looks good 👍, now let's build it 🔨..."

yarn build || (
    echo "❌ 👷‍♂️ your build failed",
    false;
)

echo "🥰 great job, you can commit it."